-- =====================================================================
-- Migration 009: Seed the full list of Malaysian universities
-- JomDekan — the university picker on registration needs the real list
-- of Malaysian public and private universities (per
-- https://studymalaysia.com/education/top-stories/list-of-universities-in-malaysia),
-- not just the 3 dev-seed examples. This ships as a migration (not
-- database/seed.sql, which is dev-only) so every environment — including
-- production — has it.
-- =====================================================================
-- Idempotent-safe: ON CONFLICT (slug) DO NOTHING, so re-running this or
-- registering additional universities later never fails or duplicates.

INSERT INTO universities (name, slug, country) VALUES
    ('Universiti Malaya', 'universiti-malaya', 'Malaysia'),
    ('Universiti Kebangsaan Malaysia', 'universiti-kebangsaan-malaysia', 'Malaysia'),
    ('Universiti Putra Malaysia', 'universiti-putra-malaysia', 'Malaysia'),
    ('Universiti Sains Malaysia', 'universiti-sains-malaysia', 'Malaysia'),
    ('Universiti Teknologi Malaysia', 'universiti-teknologi-malaysia', 'Malaysia'),
    ('Universiti Teknologi MARA', 'universiti-teknologi-mara', 'Malaysia'),
    ('Universiti Utara Malaysia', 'universiti-utara-malaysia', 'Malaysia'),
    ('Universiti Islam Antarabangsa Malaysia', 'universiti-islam-antarabangsa-malaysia', 'Malaysia'),
    ('Universiti Sains Islam Malaysia', 'universiti-sains-islam-malaysia', 'Malaysia'),
    ('Universiti Pendidikan Sultan Idris', 'universiti-pendidikan-sultan-idris', 'Malaysia'),
    ('Universiti Malaysia Sabah', 'universiti-malaysia-sabah', 'Malaysia'),
    ('Universiti Malaysia Sarawak', 'universiti-malaysia-sarawak', 'Malaysia'),
    ('Universiti Malaysia Terengganu', 'universiti-malaysia-terengganu', 'Malaysia'),
    ('Universiti Malaysia Kelantan', 'universiti-malaysia-kelantan', 'Malaysia'),
    ('Universiti Malaysia Pahang Al-Sultan Abdullah', 'universiti-malaysia-pahang-al-sultan-abdullah', 'Malaysia'),
    ('Universiti Malaysia Perlis', 'universiti-malaysia-perlis', 'Malaysia'),
    ('Universiti Teknikal Malaysia Melaka', 'universiti-teknikal-malaysia-melaka', 'Malaysia'),
    ('Universiti Tun Hussein Onn Malaysia', 'universiti-tun-hussein-onn-malaysia', 'Malaysia'),
    ('Universiti Pertahanan Nasional Malaysia', 'universiti-pertahanan-nasional-malaysia', 'Malaysia'),
    ('Universiti Sultan Zainal Abidin', 'universiti-sultan-zainal-abidin', 'Malaysia'),
    ('Universiti Tenaga Nasional', 'universiti-tenaga-nasional', 'Malaysia'),
    ('Universiti Teknologi PETRONAS', 'universiti-teknologi-petronas', 'Malaysia'),
    ('Universiti Tunku Abdul Rahman', 'universiti-tunku-abdul-rahman', 'Malaysia'),
    ('Tunku Abdul Rahman University of Management and Technology', 'tunku-abdul-rahman-university-of-management-and-technology', 'Malaysia'),
    ('Universiti Kuala Lumpur', 'universiti-kuala-lumpur', 'Malaysia'),
    ('Universiti Selangor', 'universiti-selangor', 'Malaysia'),
    ('Universiti Islam Selangor', 'universiti-islam-selangor', 'Malaysia'),
    ('Albukhary International University', 'albukhary-international-university', 'Malaysia'),
    ('Multimedia University', 'multimedia-university', 'Malaysia'),
    ('Taylor''s University', 'taylor-s-university', 'Malaysia'),
    ('Sunway University', 'sunway-university', 'Malaysia'),
    ('UCSI University', 'ucsi-university', 'Malaysia'),
    ('INTI International University', 'inti-international-university', 'Malaysia'),
    ('SEGi University', 'segi-university', 'Malaysia'),
    ('HELP University', 'help-university', 'Malaysia'),
    ('Asia Pacific University of Technology & Innovation', 'asia-pacific-university-of-technology-innovation', 'Malaysia'),
    ('Management and Science University', 'management-and-science-university', 'Malaysia'),
    ('Monash University Malaysia', 'monash-university-malaysia', 'Malaysia'),
    ('University of Nottingham Malaysia', 'university-of-nottingham-malaysia', 'Malaysia'),
    ('Xiamen University Malaysia', 'xiamen-university-malaysia', 'Malaysia'),
    ('Heriot-Watt University Malaysia', 'heriot-watt-university-malaysia', 'Malaysia'),
    ('University of Southampton Malaysia', 'university-of-southampton-malaysia', 'Malaysia'),
    ('Curtin University Malaysia', 'curtin-university-malaysia', 'Malaysia'),
    ('Swinburne University of Technology Sarawak Campus', 'swinburne-university-of-technology-sarawak-campus', 'Malaysia'),
    ('University of Reading Malaysia', 'university-of-reading-malaysia', 'Malaysia'),
    ('Newcastle University Medicine Malaysia', 'newcastle-university-medicine-malaysia', 'Malaysia'),
    ('International Medical University', 'international-medical-university', 'Malaysia'),
    ('MAHSA University', 'mahsa-university', 'Malaysia'),
    ('AIMST University', 'aimst-university', 'Malaysia'),
    ('Lincoln University College', 'lincoln-university-college', 'Malaysia'),
    ('University of Wollongong Malaysia KDU Penang University College', 'university-of-wollongong-malaysia-kdu-penang-university-college', 'Malaysia'),
    ('Wawasan Open University', 'wawasan-open-university', 'Malaysia'),
    ('Open University Malaysia', 'open-university-malaysia', 'Malaysia'),
    ('University of Cyberjaya', 'university-of-cyberjaya', 'Malaysia'),
    ('Limkokwing University of Creative Technology', 'limkokwing-university-of-creative-technology', 'Malaysia'),
    ('UNITAR International University', 'unitar-international-university', 'Malaysia'),
    ('Perdana University', 'perdana-university', 'Malaysia'),
    ('Quest International University', 'quest-international-university', 'Malaysia'),
    ('Al-Madinah International University', 'al-madinah-international-university', 'Malaysia'),
    ('Berjaya University College', 'berjaya-university-college', 'Malaysia'),
    ('First City University College', 'first-city-university-college', 'Malaysia'),
    ('Raffles University', 'raffles-university', 'Malaysia'),
    ('City University Malaysia', 'city-university-malaysia', 'Malaysia'),
    ('DRB-HICOM University of Automotive Malaysia', 'drb-hicom-university-of-automotive-malaysia', 'Malaysia'),
    ('INCEIF University', 'inceif-university', 'Malaysia'),
    ('Manipal International University', 'manipal-international-university', 'Malaysia'),
    ('Asia Metropolitan University', 'asia-metropolitan-university', 'Malaysia'),
    ('Binary University of Management & Entrepreneurship', 'binary-university-of-management-entrepreneurship', 'Malaysia'),
    ('Nilai University', 'nilai-university', 'Malaysia'),
    ('Malaysia University of Science and Technology', 'malaysia-university-of-science-and-technology', 'Malaysia'),
    ('Kolej Universiti Poly-Tech MARA', 'kolej-universiti-poly-tech-mara', 'Malaysia'),
    ('TATI University College', 'tati-university-college', 'Malaysia'),
    ('Southern University College', 'southern-university-college', 'Malaysia'),
    ('New Era University College', 'new-era-university-college', 'Malaysia'),
    ('Han Chiang University College', 'han-chiang-university-college', 'Malaysia'),
    ('SAITO University College', 'saito-university-college', 'Malaysia'),
    ('Widad University College', 'widad-university-college', 'Malaysia'),
    ('KPJ Healthcare University', 'kpj-healthcare-university', 'Malaysia'),
    ('Twintech International University College', 'twintech-international-university-college', 'Malaysia'),
    ('Global NxT University', 'global-nxt-university', 'Malaysia')
ON CONFLICT (slug) DO NOTHING;
